package com.lee.example.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CouponExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public CouponExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andSceneIsNull() {
      addCriterion("scene is null");
      return (Criteria) this;
    }

    public Criteria andSceneIsNotNull() {
      addCriterion("scene is not null");
      return (Criteria) this;
    }

    public Criteria andSceneEqualTo(Byte value) {
      addCriterion("scene =", value, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneNotEqualTo(Byte value) {
      addCriterion("scene <>", value, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneGreaterThan(Byte value) {
      addCriterion("scene >", value, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneGreaterThanOrEqualTo(Byte value) {
      addCriterion("scene >=", value, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneLessThan(Byte value) {
      addCriterion("scene <", value, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneLessThanOrEqualTo(Byte value) {
      addCriterion("scene <=", value, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneIn(List<Byte> values) {
      addCriterion("scene in", values, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneNotIn(List<Byte> values) {
      addCriterion("scene not in", values, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneBetween(Byte value1, Byte value2) {
      addCriterion("scene between", value1, value2, "scene");
      return (Criteria) this;
    }

    public Criteria andSceneNotBetween(Byte value1, Byte value2) {
      addCriterion("scene not between", value1, value2, "scene");
      return (Criteria) this;
    }

    public Criteria andVendorIdIsNull() {
      addCriterion("vendor_id is null");
      return (Criteria) this;
    }

    public Criteria andVendorIdIsNotNull() {
      addCriterion("vendor_id is not null");
      return (Criteria) this;
    }

    public Criteria andVendorIdEqualTo(Long value) {
      addCriterion("vendor_id =", value, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdNotEqualTo(Long value) {
      addCriterion("vendor_id <>", value, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdGreaterThan(Long value) {
      addCriterion("vendor_id >", value, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdGreaterThanOrEqualTo(Long value) {
      addCriterion("vendor_id >=", value, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdLessThan(Long value) {
      addCriterion("vendor_id <", value, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdLessThanOrEqualTo(Long value) {
      addCriterion("vendor_id <=", value, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdIn(List<Long> values) {
      addCriterion("vendor_id in", values, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdNotIn(List<Long> values) {
      addCriterion("vendor_id not in", values, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdBetween(Long value1, Long value2) {
      addCriterion("vendor_id between", value1, value2, "vendorId");
      return (Criteria) this;
    }

    public Criteria andVendorIdNotBetween(Long value1, Long value2) {
      addCriterion("vendor_id not between", value1, value2, "vendorId");
      return (Criteria) this;
    }

    public Criteria andCouponNameIsNull() {
      addCriterion("coupon_name is null");
      return (Criteria) this;
    }

    public Criteria andCouponNameIsNotNull() {
      addCriterion("coupon_name is not null");
      return (Criteria) this;
    }

    public Criteria andCouponNameEqualTo(String value) {
      addCriterion("coupon_name =", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameNotEqualTo(String value) {
      addCriterion("coupon_name <>", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameGreaterThan(String value) {
      addCriterion("coupon_name >", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameGreaterThanOrEqualTo(String value) {
      addCriterion("coupon_name >=", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameLessThan(String value) {
      addCriterion("coupon_name <", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameLessThanOrEqualTo(String value) {
      addCriterion("coupon_name <=", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameLike(String value) {
      addCriterion("coupon_name like", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameNotLike(String value) {
      addCriterion("coupon_name not like", value, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameIn(List<String> values) {
      addCriterion("coupon_name in", values, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameNotIn(List<String> values) {
      addCriterion("coupon_name not in", values, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameBetween(String value1, String value2) {
      addCriterion("coupon_name between", value1, value2, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponNameNotBetween(String value1, String value2) {
      addCriterion("coupon_name not between", value1, value2, "couponName");
      return (Criteria) this;
    }

    public Criteria andCouponTypeIsNull() {
      addCriterion("coupon_type is null");
      return (Criteria) this;
    }

    public Criteria andCouponTypeIsNotNull() {
      addCriterion("coupon_type is not null");
      return (Criteria) this;
    }

    public Criteria andCouponTypeEqualTo(Byte value) {
      addCriterion("coupon_type =", value, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeNotEqualTo(Byte value) {
      addCriterion("coupon_type <>", value, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeGreaterThan(Byte value) {
      addCriterion("coupon_type >", value, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeGreaterThanOrEqualTo(Byte value) {
      addCriterion("coupon_type >=", value, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeLessThan(Byte value) {
      addCriterion("coupon_type <", value, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeLessThanOrEqualTo(Byte value) {
      addCriterion("coupon_type <=", value, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeIn(List<Byte> values) {
      addCriterion("coupon_type in", values, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeNotIn(List<Byte> values) {
      addCriterion("coupon_type not in", values, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeBetween(Byte value1, Byte value2) {
      addCriterion("coupon_type between", value1, value2, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponTypeNotBetween(Byte value1, Byte value2) {
      addCriterion("coupon_type not between", value1, value2, "couponType");
      return (Criteria) this;
    }

    public Criteria andCouponNumIsNull() {
      addCriterion("coupon_num is null");
      return (Criteria) this;
    }

    public Criteria andCouponNumIsNotNull() {
      addCriterion("coupon_num is not null");
      return (Criteria) this;
    }

    public Criteria andCouponNumEqualTo(Long value) {
      addCriterion("coupon_num =", value, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumNotEqualTo(Long value) {
      addCriterion("coupon_num <>", value, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumGreaterThan(Long value) {
      addCriterion("coupon_num >", value, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumGreaterThanOrEqualTo(Long value) {
      addCriterion("coupon_num >=", value, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumLessThan(Long value) {
      addCriterion("coupon_num <", value, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumLessThanOrEqualTo(Long value) {
      addCriterion("coupon_num <=", value, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumIn(List<Long> values) {
      addCriterion("coupon_num in", values, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumNotIn(List<Long> values) {
      addCriterion("coupon_num not in", values, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumBetween(Long value1, Long value2) {
      addCriterion("coupon_num between", value1, value2, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponNumNotBetween(Long value1, Long value2) {
      addCriterion("coupon_num not between", value1, value2, "couponNum");
      return (Criteria) this;
    }

    public Criteria andCouponAmountIsNull() {
      addCriterion("coupon_amount is null");
      return (Criteria) this;
    }

    public Criteria andCouponAmountIsNotNull() {
      addCriterion("coupon_amount is not null");
      return (Criteria) this;
    }

    public Criteria andCouponAmountEqualTo(BigDecimal value) {
      addCriterion("coupon_amount =", value, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountNotEqualTo(BigDecimal value) {
      addCriterion("coupon_amount <>", value, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountGreaterThan(BigDecimal value) {
      addCriterion("coupon_amount >", value, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("coupon_amount >=", value, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountLessThan(BigDecimal value) {
      addCriterion("coupon_amount <", value, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountLessThanOrEqualTo(BigDecimal value) {
      addCriterion("coupon_amount <=", value, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountIn(List<BigDecimal> values) {
      addCriterion("coupon_amount in", values, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountNotIn(List<BigDecimal> values) {
      addCriterion("coupon_amount not in", values, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("coupon_amount between", value1, value2, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andCouponAmountNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("coupon_amount not between", value1, value2, "couponAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountIsNull() {
      addCriterion("triger_amount is null");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountIsNotNull() {
      addCriterion("triger_amount is not null");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountEqualTo(BigDecimal value) {
      addCriterion("triger_amount =", value, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountNotEqualTo(BigDecimal value) {
      addCriterion("triger_amount <>", value, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountGreaterThan(BigDecimal value) {
      addCriterion("triger_amount >", value, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("triger_amount >=", value, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountLessThan(BigDecimal value) {
      addCriterion("triger_amount <", value, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountLessThanOrEqualTo(BigDecimal value) {
      addCriterion("triger_amount <=", value, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountIn(List<BigDecimal> values) {
      addCriterion("triger_amount in", values, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountNotIn(List<BigDecimal> values) {
      addCriterion("triger_amount not in", values, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("triger_amount between", value1, value2, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andTrigerAmountNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("triger_amount not between", value1, value2, "trigerAmount");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeIsNull() {
      addCriterion("release_start_time is null");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeIsNotNull() {
      addCriterion("release_start_time is not null");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeEqualTo(Date value) {
      addCriterion("release_start_time =", value, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeNotEqualTo(Date value) {
      addCriterion("release_start_time <>", value, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeGreaterThan(Date value) {
      addCriterion("release_start_time >", value, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("release_start_time >=", value, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeLessThan(Date value) {
      addCriterion("release_start_time <", value, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeLessThanOrEqualTo(Date value) {
      addCriterion("release_start_time <=", value, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeIn(List<Date> values) {
      addCriterion("release_start_time in", values, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeNotIn(List<Date> values) {
      addCriterion("release_start_time not in", values, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeBetween(Date value1, Date value2) {
      addCriterion("release_start_time between", value1, value2, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseStartTimeNotBetween(Date value1, Date value2) {
      addCriterion("release_start_time not between", value1, value2, "releaseStartTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeIsNull() {
      addCriterion("release_end_time is null");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeIsNotNull() {
      addCriterion("release_end_time is not null");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeEqualTo(Date value) {
      addCriterion("release_end_time =", value, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeNotEqualTo(Date value) {
      addCriterion("release_end_time <>", value, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeGreaterThan(Date value) {
      addCriterion("release_end_time >", value, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("release_end_time >=", value, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeLessThan(Date value) {
      addCriterion("release_end_time <", value, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeLessThanOrEqualTo(Date value) {
      addCriterion("release_end_time <=", value, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeIn(List<Date> values) {
      addCriterion("release_end_time in", values, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeNotIn(List<Date> values) {
      addCriterion("release_end_time not in", values, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeBetween(Date value1, Date value2) {
      addCriterion("release_end_time between", value1, value2, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andReleaseEndTimeNotBetween(Date value1, Date value2) {
      addCriterion("release_end_time not between", value1, value2, "releaseEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeIsNull() {
      addCriterion("available_type is null");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeIsNotNull() {
      addCriterion("available_type is not null");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeEqualTo(Byte value) {
      addCriterion("available_type =", value, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeNotEqualTo(Byte value) {
      addCriterion("available_type <>", value, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeGreaterThan(Byte value) {
      addCriterion("available_type >", value, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeGreaterThanOrEqualTo(Byte value) {
      addCriterion("available_type >=", value, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeLessThan(Byte value) {
      addCriterion("available_type <", value, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeLessThanOrEqualTo(Byte value) {
      addCriterion("available_type <=", value, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeIn(List<Byte> values) {
      addCriterion("available_type in", values, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeNotIn(List<Byte> values) {
      addCriterion("available_type not in", values, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeBetween(Byte value1, Byte value2) {
      addCriterion("available_type between", value1, value2, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableTypeNotBetween(Byte value1, Byte value2) {
      addCriterion("available_type not between", value1, value2, "availableType");
      return (Criteria) this;
    }

    public Criteria andAvailableDayIsNull() {
      addCriterion("available_day is null");
      return (Criteria) this;
    }

    public Criteria andAvailableDayIsNotNull() {
      addCriterion("available_day is not null");
      return (Criteria) this;
    }

    public Criteria andAvailableDayEqualTo(Byte value) {
      addCriterion("available_day =", value, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayNotEqualTo(Byte value) {
      addCriterion("available_day <>", value, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayGreaterThan(Byte value) {
      addCriterion("available_day >", value, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayGreaterThanOrEqualTo(Byte value) {
      addCriterion("available_day >=", value, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayLessThan(Byte value) {
      addCriterion("available_day <", value, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayLessThanOrEqualTo(Byte value) {
      addCriterion("available_day <=", value, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayIn(List<Byte> values) {
      addCriterion("available_day in", values, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayNotIn(List<Byte> values) {
      addCriterion("available_day not in", values, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayBetween(Byte value1, Byte value2) {
      addCriterion("available_day between", value1, value2, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableDayNotBetween(Byte value1, Byte value2) {
      addCriterion("available_day not between", value1, value2, "availableDay");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeIsNull() {
      addCriterion("available_start_time is null");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeIsNotNull() {
      addCriterion("available_start_time is not null");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeEqualTo(Date value) {
      addCriterion("available_start_time =", value, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeNotEqualTo(Date value) {
      addCriterion("available_start_time <>", value, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeGreaterThan(Date value) {
      addCriterion("available_start_time >", value, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("available_start_time >=", value, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeLessThan(Date value) {
      addCriterion("available_start_time <", value, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeLessThanOrEqualTo(Date value) {
      addCriterion("available_start_time <=", value, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeIn(List<Date> values) {
      addCriterion("available_start_time in", values, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeNotIn(List<Date> values) {
      addCriterion("available_start_time not in", values, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeBetween(Date value1, Date value2) {
      addCriterion("available_start_time between", value1, value2, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableStartTimeNotBetween(Date value1, Date value2) {
      addCriterion("available_start_time not between", value1, value2, "availableStartTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeIsNull() {
      addCriterion("available_end_time is null");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeIsNotNull() {
      addCriterion("available_end_time is not null");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeEqualTo(Date value) {
      addCriterion("available_end_time =", value, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeNotEqualTo(Date value) {
      addCriterion("available_end_time <>", value, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeGreaterThan(Date value) {
      addCriterion("available_end_time >", value, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("available_end_time >=", value, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeLessThan(Date value) {
      addCriterion("available_end_time <", value, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeLessThanOrEqualTo(Date value) {
      addCriterion("available_end_time <=", value, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeIn(List<Date> values) {
      addCriterion("available_end_time in", values, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeNotIn(List<Date> values) {
      addCriterion("available_end_time not in", values, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeBetween(Date value1, Date value2) {
      addCriterion("available_end_time between", value1, value2, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andAvailableEndTimeNotBetween(Date value1, Date value2) {
      addCriterion("available_end_time not between", value1, value2, "availableEndTime");
      return (Criteria) this;
    }

    public Criteria andProductRangeIsNull() {
      addCriterion("product_range is null");
      return (Criteria) this;
    }

    public Criteria andProductRangeIsNotNull() {
      addCriterion("product_range is not null");
      return (Criteria) this;
    }

    public Criteria andProductRangeEqualTo(Byte value) {
      addCriterion("product_range =", value, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeNotEqualTo(Byte value) {
      addCriterion("product_range <>", value, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeGreaterThan(Byte value) {
      addCriterion("product_range >", value, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeGreaterThanOrEqualTo(Byte value) {
      addCriterion("product_range >=", value, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeLessThan(Byte value) {
      addCriterion("product_range <", value, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeLessThanOrEqualTo(Byte value) {
      addCriterion("product_range <=", value, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeIn(List<Byte> values) {
      addCriterion("product_range in", values, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeNotIn(List<Byte> values) {
      addCriterion("product_range not in", values, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeBetween(Byte value1, Byte value2) {
      addCriterion("product_range between", value1, value2, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeNotBetween(Byte value1, Byte value2) {
      addCriterion("product_range not between", value1, value2, "productRange");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutIsNull() {
      addCriterion("product_range_without is null");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutIsNotNull() {
      addCriterion("product_range_without is not null");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutEqualTo(Byte value) {
      addCriterion("product_range_without =", value, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutNotEqualTo(Byte value) {
      addCriterion("product_range_without <>", value, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutGreaterThan(Byte value) {
      addCriterion("product_range_without >", value, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutGreaterThanOrEqualTo(Byte value) {
      addCriterion("product_range_without >=", value, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutLessThan(Byte value) {
      addCriterion("product_range_without <", value, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutLessThanOrEqualTo(Byte value) {
      addCriterion("product_range_without <=", value, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutIn(List<Byte> values) {
      addCriterion("product_range_without in", values, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutNotIn(List<Byte> values) {
      addCriterion("product_range_without not in", values, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutBetween(Byte value1, Byte value2) {
      addCriterion("product_range_without between", value1, value2, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andProductRangeWithoutNotBetween(Byte value1, Byte value2) {
      addCriterion("product_range_without not between", value1, value2, "productRangeWithout");
      return (Criteria) this;
    }

    public Criteria andShopRangeIsNull() {
      addCriterion("shop_range is null");
      return (Criteria) this;
    }

    public Criteria andShopRangeIsNotNull() {
      addCriterion("shop_range is not null");
      return (Criteria) this;
    }

    public Criteria andShopRangeEqualTo(Byte value) {
      addCriterion("shop_range =", value, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeNotEqualTo(Byte value) {
      addCriterion("shop_range <>", value, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeGreaterThan(Byte value) {
      addCriterion("shop_range >", value, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeGreaterThanOrEqualTo(Byte value) {
      addCriterion("shop_range >=", value, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeLessThan(Byte value) {
      addCriterion("shop_range <", value, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeLessThanOrEqualTo(Byte value) {
      addCriterion("shop_range <=", value, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeIn(List<Byte> values) {
      addCriterion("shop_range in", values, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeNotIn(List<Byte> values) {
      addCriterion("shop_range not in", values, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeBetween(Byte value1, Byte value2) {
      addCriterion("shop_range between", value1, value2, "shopRange");
      return (Criteria) this;
    }

    public Criteria andShopRangeNotBetween(Byte value1, Byte value2) {
      addCriterion("shop_range not between", value1, value2, "shopRange");
      return (Criteria) this;
    }

    public Criteria andLimitNumIsNull() {
      addCriterion("limit_num is null");
      return (Criteria) this;
    }

    public Criteria andLimitNumIsNotNull() {
      addCriterion("limit_num is not null");
      return (Criteria) this;
    }

    public Criteria andLimitNumEqualTo(Long value) {
      addCriterion("limit_num =", value, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumNotEqualTo(Long value) {
      addCriterion("limit_num <>", value, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumGreaterThan(Long value) {
      addCriterion("limit_num >", value, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumGreaterThanOrEqualTo(Long value) {
      addCriterion("limit_num >=", value, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumLessThan(Long value) {
      addCriterion("limit_num <", value, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumLessThanOrEqualTo(Long value) {
      addCriterion("limit_num <=", value, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumIn(List<Long> values) {
      addCriterion("limit_num in", values, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumNotIn(List<Long> values) {
      addCriterion("limit_num not in", values, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumBetween(Long value1, Long value2) {
      addCriterion("limit_num between", value1, value2, "limitNum");
      return (Criteria) this;
    }

    public Criteria andLimitNumNotBetween(Long value1, Long value2) {
      addCriterion("limit_num not between", value1, value2, "limitNum");
      return (Criteria) this;
    }

    public Criteria andStatusIsNull() {
      addCriterion("status is null");
      return (Criteria) this;
    }

    public Criteria andStatusIsNotNull() {
      addCriterion("status is not null");
      return (Criteria) this;
    }

    public Criteria andStatusEqualTo(String value) {
      addCriterion("status =", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotEqualTo(String value) {
      addCriterion("status <>", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThan(String value) {
      addCriterion("status >", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThanOrEqualTo(String value) {
      addCriterion("status >=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThan(String value) {
      addCriterion("status <", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThanOrEqualTo(String value) {
      addCriterion("status <=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLike(String value) {
      addCriterion("status like", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotLike(String value) {
      addCriterion("status not like", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusIn(List<String> values) {
      addCriterion("status in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotIn(List<String> values) {
      addCriterion("status not in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusBetween(String value1, String value2) {
      addCriterion("status between", value1, value2, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotBetween(String value1, String value2) {
      addCriterion("status not between", value1, value2, "status");
      return (Criteria) this;
    }

    public Criteria andCouponExplainIsNull() {
      addCriterion("coupon_explain is null");
      return (Criteria) this;
    }

    public Criteria andCouponExplainIsNotNull() {
      addCriterion("coupon_explain is not null");
      return (Criteria) this;
    }

    public Criteria andCouponExplainEqualTo(String value) {
      addCriterion("coupon_explain =", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainNotEqualTo(String value) {
      addCriterion("coupon_explain <>", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainGreaterThan(String value) {
      addCriterion("coupon_explain >", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainGreaterThanOrEqualTo(String value) {
      addCriterion("coupon_explain >=", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainLessThan(String value) {
      addCriterion("coupon_explain <", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainLessThanOrEqualTo(String value) {
      addCriterion("coupon_explain <=", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainLike(String value) {
      addCriterion("coupon_explain like", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainNotLike(String value) {
      addCriterion("coupon_explain not like", value, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainIn(List<String> values) {
      addCriterion("coupon_explain in", values, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainNotIn(List<String> values) {
      addCriterion("coupon_explain not in", values, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainBetween(String value1, String value2) {
      addCriterion("coupon_explain between", value1, value2, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCouponExplainNotBetween(String value1, String value2) {
      addCriterion("coupon_explain not between", value1, value2, "couponExplain");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentIsNull() {
      addCriterion("create_department is null");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentIsNotNull() {
      addCriterion("create_department is not null");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentEqualTo(String value) {
      addCriterion("create_department =", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentNotEqualTo(String value) {
      addCriterion("create_department <>", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentGreaterThan(String value) {
      addCriterion("create_department >", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentGreaterThanOrEqualTo(String value) {
      addCriterion("create_department >=", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentLessThan(String value) {
      addCriterion("create_department <", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentLessThanOrEqualTo(String value) {
      addCriterion("create_department <=", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentLike(String value) {
      addCriterion("create_department like", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentNotLike(String value) {
      addCriterion("create_department not like", value, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentIn(List<String> values) {
      addCriterion("create_department in", values, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentNotIn(List<String> values) {
      addCriterion("create_department not in", values, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentBetween(String value1, String value2) {
      addCriterion("create_department between", value1, value2, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andCreateDepartmentNotBetween(String value1, String value2) {
      addCriterion("create_department not between", value1, value2, "createDepartment");
      return (Criteria) this;
    }

    public Criteria andSysVersionIsNull() {
      addCriterion("sys_version is null");
      return (Criteria) this;
    }

    public Criteria andSysVersionIsNotNull() {
      addCriterion("sys_version is not null");
      return (Criteria) this;
    }

    public Criteria andSysVersionEqualTo(Integer value) {
      addCriterion("sys_version =", value, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionNotEqualTo(Integer value) {
      addCriterion("sys_version <>", value, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionGreaterThan(Integer value) {
      addCriterion("sys_version >", value, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionGreaterThanOrEqualTo(Integer value) {
      addCriterion("sys_version >=", value, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionLessThan(Integer value) {
      addCriterion("sys_version <", value, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionLessThanOrEqualTo(Integer value) {
      addCriterion("sys_version <=", value, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionIn(List<Integer> values) {
      addCriterion("sys_version in", values, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionNotIn(List<Integer> values) {
      addCriterion("sys_version not in", values, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionBetween(Integer value1, Integer value2) {
      addCriterion("sys_version between", value1, value2, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andSysVersionNotBetween(Integer value1, Integer value2) {
      addCriterion("sys_version not between", value1, value2, "sysVersion");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNull() {
      addCriterion("create_time is null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNotNull() {
      addCriterion("create_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeEqualTo(Date value) {
      addCriterion("create_time =", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotEqualTo(Date value) {
      addCriterion("create_time <>", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThan(Date value) {
      addCriterion("create_time >", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("create_time >=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThan(Date value) {
      addCriterion("create_time <", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
      addCriterion("create_time <=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIn(List<Date> values) {
      addCriterion("create_time in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotIn(List<Date> values) {
      addCriterion("create_time not in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeBetween(Date value1, Date value2) {
      addCriterion("create_time between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
      addCriterion("create_time not between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateUserIsNull() {
      addCriterion("create_user is null");
      return (Criteria) this;
    }

    public Criteria andCreateUserIsNotNull() {
      addCriterion("create_user is not null");
      return (Criteria) this;
    }

    public Criteria andCreateUserEqualTo(String value) {
      addCriterion("create_user =", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotEqualTo(String value) {
      addCriterion("create_user <>", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserGreaterThan(String value) {
      addCriterion("create_user >", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
      addCriterion("create_user >=", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserLessThan(String value) {
      addCriterion("create_user <", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserLessThanOrEqualTo(String value) {
      addCriterion("create_user <=", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserLike(String value) {
      addCriterion("create_user like", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotLike(String value) {
      addCriterion("create_user not like", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserIn(List<String> values) {
      addCriterion("create_user in", values, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotIn(List<String> values) {
      addCriterion("create_user not in", values, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserBetween(String value1, String value2) {
      addCriterion("create_user between", value1, value2, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotBetween(String value1, String value2) {
      addCriterion("create_user not between", value1, value2, "createUser");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNull() {
      addCriterion("update_time is null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNotNull() {
      addCriterion("update_time is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeEqualTo(Date value) {
      addCriterion("update_time =", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotEqualTo(Date value) {
      addCriterion("update_time <>", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThan(Date value) {
      addCriterion("update_time >", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("update_time >=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThan(Date value) {
      addCriterion("update_time <", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
      addCriterion("update_time <=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIn(List<Date> values) {
      addCriterion("update_time in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotIn(List<Date> values) {
      addCriterion("update_time not in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeBetween(Date value1, Date value2) {
      addCriterion("update_time between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
      addCriterion("update_time not between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateUserIsNull() {
      addCriterion("update_user is null");
      return (Criteria) this;
    }

    public Criteria andUpdateUserIsNotNull() {
      addCriterion("update_user is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateUserEqualTo(String value) {
      addCriterion("update_user =", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotEqualTo(String value) {
      addCriterion("update_user <>", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserGreaterThan(String value) {
      addCriterion("update_user >", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
      addCriterion("update_user >=", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserLessThan(String value) {
      addCriterion("update_user <", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserLessThanOrEqualTo(String value) {
      addCriterion("update_user <=", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserLike(String value) {
      addCriterion("update_user like", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotLike(String value) {
      addCriterion("update_user not like", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserIn(List<String> values) {
      addCriterion("update_user in", values, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotIn(List<String> values) {
      addCriterion("update_user not in", values, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserBetween(String value1, String value2) {
      addCriterion("update_user between", value1, value2, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotBetween(String value1, String value2) {
      addCriterion("update_user not between", value1, value2, "updateUser");
      return (Criteria) this;
    }

    public Criteria andYnIsNull() {
      addCriterion("yn is null");
      return (Criteria) this;
    }

    public Criteria andYnIsNotNull() {
      addCriterion("yn is not null");
      return (Criteria) this;
    }

    public Criteria andYnEqualTo(Integer value) {
      addCriterion("yn =", value, "yn");
      return (Criteria) this;
    }

    public Criteria andYnNotEqualTo(Integer value) {
      addCriterion("yn <>", value, "yn");
      return (Criteria) this;
    }

    public Criteria andYnGreaterThan(Integer value) {
      addCriterion("yn >", value, "yn");
      return (Criteria) this;
    }

    public Criteria andYnGreaterThanOrEqualTo(Integer value) {
      addCriterion("yn >=", value, "yn");
      return (Criteria) this;
    }

    public Criteria andYnLessThan(Integer value) {
      addCriterion("yn <", value, "yn");
      return (Criteria) this;
    }

    public Criteria andYnLessThanOrEqualTo(Integer value) {
      addCriterion("yn <=", value, "yn");
      return (Criteria) this;
    }

    public Criteria andYnIn(List<Integer> values) {
      addCriterion("yn in", values, "yn");
      return (Criteria) this;
    }

    public Criteria andYnNotIn(List<Integer> values) {
      addCriterion("yn not in", values, "yn");
      return (Criteria) this;
    }

    public Criteria andYnBetween(Integer value1, Integer value2) {
      addCriterion("yn between", value1, value2, "yn");
      return (Criteria) this;
    }

    public Criteria andYnNotBetween(Integer value1, Integer value2) {
      addCriterion("yn not between", value1, value2, "yn");
      return (Criteria) this;
    }

    public Criteria andDiscountRateIsNull() {
      addCriterion("discount_rate is null");
      return (Criteria) this;
    }

    public Criteria andDiscountRateIsNotNull() {
      addCriterion("discount_rate is not null");
      return (Criteria) this;
    }

    public Criteria andDiscountRateEqualTo(Integer value) {
      addCriterion("discount_rate =", value, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateNotEqualTo(Integer value) {
      addCriterion("discount_rate <>", value, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateGreaterThan(Integer value) {
      addCriterion("discount_rate >", value, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateGreaterThanOrEqualTo(Integer value) {
      addCriterion("discount_rate >=", value, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateLessThan(Integer value) {
      addCriterion("discount_rate <", value, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateLessThanOrEqualTo(Integer value) {
      addCriterion("discount_rate <=", value, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateIn(List<Integer> values) {
      addCriterion("discount_rate in", values, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateNotIn(List<Integer> values) {
      addCriterion("discount_rate not in", values, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateBetween(Integer value1, Integer value2) {
      addCriterion("discount_rate between", value1, value2, "discountRate");
      return (Criteria) this;
    }

    public Criteria andDiscountRateNotBetween(Integer value1, Integer value2) {
      addCriterion("discount_rate not between", value1, value2, "discountRate");
      return (Criteria) this;
    }

    public Criteria andIsReminderIsNull() {
      addCriterion("is_reminder is null");
      return (Criteria) this;
    }

    public Criteria andIsReminderIsNotNull() {
      addCriterion("is_reminder is not null");
      return (Criteria) this;
    }

    public Criteria andIsReminderEqualTo(Byte value) {
      addCriterion("is_reminder =", value, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderNotEqualTo(Byte value) {
      addCriterion("is_reminder <>", value, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderGreaterThan(Byte value) {
      addCriterion("is_reminder >", value, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderGreaterThanOrEqualTo(Byte value) {
      addCriterion("is_reminder >=", value, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderLessThan(Byte value) {
      addCriterion("is_reminder <", value, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderLessThanOrEqualTo(Byte value) {
      addCriterion("is_reminder <=", value, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderIn(List<Byte> values) {
      addCriterion("is_reminder in", values, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderNotIn(List<Byte> values) {
      addCriterion("is_reminder not in", values, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderBetween(Byte value1, Byte value2) {
      addCriterion("is_reminder between", value1, value2, "isReminder");
      return (Criteria) this;
    }

    public Criteria andIsReminderNotBetween(Byte value1, Byte value2) {
      addCriterion("is_reminder not between", value1, value2, "isReminder");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table tb_coupon
   *
   * @mbg.generated do_not_delete_during_merge Wed Jul 25 18:14:09 CST 2018
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table tb_coupon
   *
   * @mbg.generated Wed Jul 25 18:14:09 CST 2018
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}