druid:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
      url: jdbc:mysql://localhost:33065/replicas_db?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 5
      min-idle: 1
      max-active: 100
      test-on-borrow: true
  slave:
      url: jdbc:mysql://localhost:33066/replicas_db?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 5
      min-idle: 1
      max-active: 100
      test-on-borrow: true

logging:
  level:
    root: INFO
    io:
      ostenant:
        springboot:
          sample:
            mapper: DEBUG
