security:
  oauth2:
    client:
      client-id: oauth2_client
      client-secret: oauth2_client_secret
      scope: read, write
      auto-approve-scopes: .*
      authorized-grant-types: authorization_code
      registered-redirect-uri: http://localhost:8080/login,http://localhost:8080/notes
    authorization:
      check-token-access: permitAll()
server:
  port: 8081
  servlet:
    context-path: /authserver
    session:
      cookie:
        name: auth_server

logging:
  level:
    root: DEBUG
    org.springframework.security: INFO

client:
  url: http://localhost:8080

spring:
  security:
    user:
      password: 123456
