DROP TABLE TEENAGER IF EXISTS;
DROP TABLE YOUNGADULT IF EXISTS;
DROP TABLE SENIORCITIZENS IF EXISTS;

CREATE TABLE TEENAGER  (
    person_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20)
);

CREATE TABLE YOUNGADULT  (
    person_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20)
);

CREATE TABLE SENIORCITIZENS  (
    person_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20)
);
