auth-jwt:
  keystore-alias: jwt
  keystore-filename: jwt.jks
  keypass: mySecretKey
  storepass: mySecretKey

server:
  port: 8081
  servlet:
    context-path: /authserver

logging:
  level:
    org.springframework.security: DEBUG

client:
  url: http://localhost:8080