server:
  port: 9082
# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 配置参考：https://www.cnblogs.com/babycomeon/p/11161073.html
spring:
  application:
    name: gateway-reactor-gray
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hello-consumer
          uri: grayLb://hello-consumer
          predicates:
            - Path=/hello/**
        # 通过访问http://localhost:9082/test/v1,来测试权重
        - id: hello-consumer-v1
          uri: lb://hello-consumer
          predicates:
            - Path=/test/**
            - Weight=group1, 8
          filters:
            - AddRequestHeader=hello, world
        - id: hello-consumer-v2
          uri: lb://hello-consumer
          predicates:
            - Path=/test/**
            - Weight=group1, 2
          filters:
            - StripPrefix=1

