package com.us.example.model;

/**
 * @author litz-a
 */
public class Permission {

  private int id;

  /**
   * 权限名称
   */
  private String name;

  /**
   * 权限描述
   */
  private String descritpion;

  /**
   * 授权链接
   */
  private String url;

  /**
   * 父节点id
   */
  private int pid;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.id
   *
   * @return the value of sys_permission.id
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.id
   *
   * @param id the value for sys_permission.id
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.name
   *
   * @return the value of sys_permission.name
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.name
   *
   * @param name the value for sys_permission.name
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.descritpion
   *
   * @return the value of sys_permission.descritpion
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public String getDescritpion() {
    return descritpion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.descritpion
   *
   * @param descritpion the value for sys_permission.descritpion
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public void setDescritpion(String descritpion) {
    this.descritpion = descritpion == null ? null : descritpion.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.url
   *
   * @return the value of sys_permission.url
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public String getUrl() {
    return url;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.url
   *
   * @param url the value for sys_permission.url
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public void setUrl(String url) {
    this.url = url == null ? null : url.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column sys_permission.pid
   *
   * @return the value of sys_permission.pid
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public Integer getPid() {
    return pid;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column sys_permission.pid
   *
   * @param pid the value for sys_permission.pid
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public void setPid(Integer pid) {
    this.pid = pid;
  }
}