package com.us.example.model;

public class Role {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.id
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.name
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  private String name;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.id
   *
   * @return the value of sys_role.id
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.id
   *
   * @param id the value for sys_role.id
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.name
   *
   * @return the value of sys_role.name
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.name
   *
   * @param name the value for sys_role.name
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }
}