create table OAUTH_ACCESS_TOKEN
(
  TOKEN_ID          VARCHAR2(256),
  AUTHENTICATION_ID VARCHAR2(256) not null,
  USER_NAME         VARCHAR2(256),
  CLIENT_ID         VARCHAR2(256),
  REFRESH_TOKEN     VARCHAR2(256),
  TOKEN             BLOB,
  AUTHENTICATION    BLOB
);

create table OAUTH_APPROVALS
(
  USERID         VARCHAR2(256),
  CLIENTID       VARCHAR2(256),
  SCOPE          VARCHAR2(256),
  STATUS         VARCHAR2(10),
  EXPIRESAT      TIMESTAMP(6),
  LASTMODIFIEDAT TIMESTAMP(6)
);

create table OAUTH_CLIENT_DETAILS
(
  CLIENT_ID               VARCHAR2(256) not null,
  RESOURCE_IDS            VARCHAR2(256),
  CLIENT_SECRET           VARCHAR2(256),
  SCOPE                   VARCHAR2(256),
  AUTHORIZED_GRANT_TYPES  VARCHAR2(256),
  WEB_SERVER_REDIRECT_URI VARCHAR2(256),
  AUTHORITIES             VARCHAR2(256),
  ACCESS_TOKEN_VALIDITY   INTEGER,
  REFRESH_TOKEN_VALIDITY  INTEGER,
  ADDITIONAL_INFORMATION  VARCHAR2(1024),
  AUTOAPPROVE             VARCHAR2(256)
);

create table OAUTH_CLIENT_TOKEN
(
  TOKEN_ID          VARCHAR2(256),
  TOKEN             NUMBER(30),
  AUTHENTICATION_ID VARCHAR2(256) not null,
  USER_NAME         VARCHAR2(256),
  CLIENT_ID         VARCHAR2(256)
);

create table OAUTH_CODE
(
  CODE           VARCHAR2(256),
  AUTHENTICATION NUMBER(30)
);

create table OAUTH_REFRESH_TOKEN
(
  TOKEN_ID       VARCHAR2(256),
  TOKEN          NUMBER(30),
  AUTHENTICATION NUMBER(30)
);