spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  type-aliases-package: org.lee.mybatis.page.model
  mapper-locations: mapper/*.xml

logging:
  level:
    root: INFO
    org:
      lee:
        mybatis:
          page:
            mapper: debug
