spring:
  datasource:
    ## Primary 数据源配置
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/db1_department?useUnicode=true&characterEncoding=utf-8
   username: root
   password: root
   # 最大活跃数
   maxActive: 20
   # 打开PSCache，并且指定每个连接PSCache的大小
   poolPreparedStatements: true
   maxPoolPreparedStatementPerConnectionSize: 20
   minIdle: 1
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: select 1 from dual
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
