spring:
  profiles:
    active: dev
  application:
    name: hello-consumer
---
server:
  port: 7082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v1
  profiles: dev

---
server:
  port: 17083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v2
  profiles: prod


