# =============================================
# = Google Recaptcha configurations
# = https://www.google.com/recaptcha/admin#list
# =============================================
google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key: <enter-key-here>
    secret: <enter-secret-here>


# =============================================
# = Logging configurations
# =============================================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO