spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  type-aliases-package: org.ostenant.springboot.learning.examples.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: INFO
    org:
      ostenant:
        springboot:
          learning:
            examples:
              mapper: debug