spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
#    org.hibernate.SQL: debug                #等价于spring.jpa.show-sql=true
    org.hibernate.type.descriptor.sql: trace #显示sql语句中param的值

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
