auth-server: http://localhost:8081/authserver
server:
  port: 8082
  servlet:
    context-path: /resource
    session:
      cookie:
        name: resource_server
spring:
  datasource:
    platform: h2
security:
  oauth2:
    client:
      client-id: oauth2_client
      client-secret: oauth2_client_secret
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework.security: DEBUG