spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/sales
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         google:
          client-id: YOUR_GOOGLE_CLIENT_ID
          clientSecret: YOUR_GOOGLE_CLIENT_SECRET
          scope:
           - email
           - profile