spring:
  application:
    name: hystrix-turbine-amqp

  rabbitmq:
    addresses: 10.1.70.92
    port: 5672
    username: admin
    password: admin


server:
  port: 9260

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
