mongodb:
  primary:
    host: localhost
    port: 27017
    database: primary
  secondary:
    host: localhost
    port: 27017
    database: second

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration