package com.us.example.dao;

import com.us.example.model.User;
import com.us.example.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  long countByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  int deleteByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  @Delete({
      "delete from sys_user",
      "where id = #{id,jdbcType=INTEGER}"
  })
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  @Insert({
      "insert into sys_user (id, username, ",
      "password)",
      "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
      "#{password,jdbcType=VARCHAR})"
  })
  int insert(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  int insertSelective(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  List<User> selectByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  @Select({
      "select",
      "user.id as user_id, user.username as user_username, user.password as user_password",
      "from sys_user user",
      "where user.id = #{id,jdbcType=INTEGER}"
  })
  @ResultMap("com.us.example.dao.UserMapper.BaseResultMap")
  User selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  int updateByExample(@Param("record") User record, @Param("example") UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  int updateByPrimaryKeySelective(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user
   *
   * @mbg.generated Fri Aug 24 08:56:53 CST 2018
   */
  @Update({
      "update sys_user",
      "set username = #{username,jdbcType=VARCHAR},",
      "password = #{password,jdbcType=VARCHAR}",
      "where id = #{id,jdbcType=INTEGER}"
  })
  int updateByPrimaryKey(User record);


  /**
   * findByUserName
   */
  User findByUserName(String username);
}