spring:
  rabbitmq:
    host: 192.168.144.45
    username: admin
    password: admin
    virtual-host: /
    listener:
      retry:
        enabled: true
        initial-interval: 2000
        max-attempts: 2
        multiplier: 1.5
        max-interval: 5000